### ISSUE TITLE
Error occurred in poll cycle: Request Timeout

### ISSUE THREAD

**Issue by JohnSundarraj** [basho/newrelic_riak_plugin#1]
Hi there, i have setup riak agent for monitoring riak node.  I'm able to successfully start the agent, but all i get is this...

```
[2013-12-10 07:26:04 UTC] INFO: Using Ruby SDK version: 1.3.1
[2013-12-10 07:26:04 UTC] INFO: Agent Riak is at version 0.1.0
[2013-12-10 07:26:04 UTC] DEBUG: Start collecting agent data for poll cycle
[2013-12-10 07:28:04 UTC] ERROR: Error occurred in poll cycle: Request Timeout
[2013-12-10 07:28:04 UTC] DEBUG: Stacktrace:
/usr/local/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:184:in `rescue in transmit'
/usr/local/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:140:in `transmit'
/usr/local/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:64:in `execute'
/usr/local/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient/request.rb:33:in `execute'
/usr/local/lib/ruby/gems/2.0.0/gems/rest-client-1.6.7/lib/restclient.rb:68:in `get'
./riak_agent.rb:130:in `poll_cycle'
/usr/local/lib/ruby/gems/2.0.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/agent.rb:139:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:143:in `block in run_agent_data_collection'
/usr/local/lib/ruby/gems/2.0.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:141:in `run_agent_data_collection'
/usr/local/lib/ruby/gems/2.0.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:127:in `loop_forever'
/usr/local/lib/ruby/gems/2.0.0/gems/newrelic_plugin-1.3.1/lib/newrelic_plugin/run.rb:15:in `setup_and_run'
./riak_agent.rb:143:in `<module:RiakAgent>'
./riak_agent.rb:8:in `<main>'
[2013-12-10 07:28:04 UTC] DEBUG: Finished collecting agent data for poll cycle
[2013-12-10 07:28:04 UTC] DEBUG: Component with name "0.0.0.0:1001" and guid "com.basho.riak_agent" had no metrics
[2013-12-10 07:28:04 UTC] DEBUG: JSON payload: {"agent":{"version":"0.1.0"},"components":[]}
[2013-12-10 07:28:04 UTC] INFO: Gathered 0 statistics from 0 components
```

I observe nothing comes to my newrelic dashboard, but my riak node is up and running. I dont know why the request gets timeout. Need help on this issue.....Correct me if i'm wrong anywhere.

**Comment by dmitrizagidulin** [comment]
Issue seems resolved, closing.
